# Perturbation Evaluation Metrics

## Load Files

In [1]:
import glob
import os
import pandas as pd

# Path to your folder
folder_path = "/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results/evaluation files"   # <-- change this

# Get all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

print(f"Found {len(csv_files)} files")

# Load and combine
dfs = []
for file in csv_files:
    df = pd.read_csv(file)
    
    # Add filename as metadata (IMPORTANT)
    df["file_name"] = os.path.basename(file)
    
    dfs.append(df)

# Combine into one dataframe
df_all = pd.concat(dfs, ignore_index=True)

df_all.head()

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1863026/2652985605.py", line 3, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1863026/2652985605.py", line 3, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1863026/2652985605.py", line 3, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1863026/2652985605.py", line 3, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

Found 45 files

,UID,dataset,model,xai_method,mode,predicted_class,auc,replacement,file_name
0,02F4A1FB_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.628240,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv
1,02F4A1FB_right,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.556623,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv
2,08FEB48B_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,2,0.416956,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv
3,1647533552_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.448901,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv
4,1647533552_right,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.367227,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv

## Micro Average

In [2]:
micro_summary = (
    df_all.groupby(["mode", "xai_method", "replacement"])["auc"]
    .agg(["mean", "std", "count"])
    .reset_index()
)
micro_summary["mean"] = micro_summary["mean"].round(3)
micro_summary["std"] = micro_summary["std"].round(3)
print("=== Micro-average (overall) ===")
micro_summary

=== Micro-average (overall) ===

         mode              xai_method        replacement   mean    std  count
0    deletion                 gradcam     attention_mask  0.426  0.196    116
1    deletion                 gradcam            black-5  0.315  0.148    116
2    deletion                 gradcam      gaussian_blur  0.416  0.197    116
3    deletion                 gradcam  minimum-intensity  0.445  0.239    116
4    deletion                 gradcam            white-5  0.290  0.118    116
5    deletion              last_layer     attention_mask  0.533  0.207    116
6    deletion              last_layer            black-5  0.321  0.150    116
7    deletion              last_layer      gaussian_blur  0.466  0.225    116
8    deletion              last_layer  minimum-intensity  0.455  0.196    116
9    deletion              last_layer            white-5  0.381  0.124    116
10   deletion  slice_weighted_rollout     attention_mask  0.480  0.161    116
11   deletion  slice_weighted_rollout            black-5  0.361  0.188    116
12   deletion  slice_weighted_rollout      gaussian_blur  0.482  0.243    116
13   deletion  slice_weighted_rollout  minimum-intensity  0.484  0.208    116
14   deletion  slice_weighted_rollout            white-5  0.393  0.146    116
15  insertion                 gradcam     attention_mask  0.795  0.111    116
16  insertion                 gradcam            black-5  0.528  0.143    116
17  insertion                 gradcam      gaussian_blur  0.644  0.117    116
18  insertion                 gradcam  minimum-intensity  0.785  0.103    116
19  insertion                 gradcam            white-5  0.672  0.130    116
20  insertion              last_layer     attention_mask  0.762  0.155    116
21  insertion              last_layer            black-5  0.517  0.179    116
22  insertion              last_layer      gaussian_blur  0.569  0.164    116
23  insertion              last_layer  minimum-intensity  0.753  0.152    116
24  insertion              last_layer            white-5  0.530  0.202    116
25  insertion  slice_weighted_rollout     attention_mask  0.793  0.129    116
26  insertion  slice_weighted_rollout            black-5  0.584  0.150    116
27  insertion  slice_weighted_rollout      gaussian_blur  0.585  0.188    116
28  insertion  slice_weighted_rollout  minimum-intensity  0.760  0.138    116
29  insertion  slice_weighted_rollout            white-5  0.580  0.184    116
30   negative                 gradcam     attention_mask  0.795  0.110    116
31   negative                 gradcam            black-5  0.529  0.139    116
32   negative                 gradcam      gaussian_blur  0.643  0.117    116
33   negative                 gradcam  minimum-intensity  0.784  0.103    116
34   negative                 gradcam            white-5  0.671  0.133    116
35   negative              last_layer     attention_mask  0.762  0.155    116
36   negative              last_layer            black-5  0.517  0.180    116
37   negative              last_layer      gaussian_blur  0.569  0.164    116
38   negative              last_layer  minimum-intensity  0.754  0.151    116
39   negative              last_layer            white-5  0.530  0.202    116
40   negative  slice_weighted_rollout     attention_mask  0.793  0.129    116
41   negative  slice_weighted_rollout            black-5  0.584  0.150    116
42   negative  slice_weighted_rollout      gaussian_blur  0.585  0.188    116
43   negative  slice_weighted_rollout  minimum-intensity  0.761  0.137    116
44   negative  slice_weighted_rollout            white-5  0.581  0.184    116

## Class-wise

In [3]:
class_summary = (
    df_all.groupby(["mode", "xai_method", "replacement", "predicted_class"])["auc"]
    .agg(["mean", "std", "count"])
    .reset_index()
)

class_summary["mean"] = class_summary["mean"].round(3)
class_summary["std"] = class_summary["std"].round(3)

print("=== Class-wise (macro view) ===")
# Source - https://stackoverflow.com/a/16433953
# Posted by Wouter Overmeire, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-25, License - CC BY-SA 4.0

pd.set_option('display.max_rows', 500)

class_summary

=== Class-wise (macro view) ===

,mode,xai_method,replacement,predicted_class,mean,std,count
0,deletion,gradcam,attention_mask,0,0.527,0.150,73
1,deletion,gradcam,attention_mask,1,0.382,0.064,21
2,deletion,gradcam,attention_mask,2,0.136,0.056,22
3,deletion,gradcam,black-5,0,0.376,0.146,73
4,deletion,gradcam,black-5,1,0.264,0.063,21
5,deletion,gradcam,black-5,2,0.162,0.054,22
6,deletion,gradcam,gaussian_blur,0,0.541,0.126,73
7,deletion,gradcam,gaussian_blur,1,0.177,0.038,21
8,deletion,gradcam,gaussian_blur,2,0.231,0.099,22
9,deletion,gradcam,minimum-intensity,0,0.599,0.155,73
10,deletion,gradcam,minimum-intensity,1,0.205,0.060,21
11,deletion,gradcam,minimum-intensity,2,0.164,0.056,22
12,deletion,gradcam,white-5,0,0.348,0.089,73
13,deletion,gradcam,white-5,1,0.229,0.070,21
14,deletion,gradcam,white-5,2,0.159,0.105,22
15,deletion,last_layer,attention_mask,0,0.658,0.101,73
16,deletion,last_layer,attention_mask,1,0.416,0.104,21
17,deletion,last_layer,attention_mask,2,0.233,0.163,22
18,deletion,last_layer,black-5,0,0.391,0.137,73
19,deletion,last_layer,black-5,1,0.223,0.073,21
20,deletion,last_layer,black-5,2,0.182,0.083,22
21,deletion,last_layer,gaussian_blur,0,0.609,0.136,73
22,deletion,last_layer,gaussian_blur,1,0.187,0.062,21
23,deletion,last_layer,gaussian_blur,2,0.259,0.126,22
24,deletion,last_layer,minimum-intensity,0,0.579,0.118,73
25,deletion,last_layer,minimum-intensity,1,0.280,0.090,21
26,deletion,last_layer,minimum-intensity,2,0.212,0.093,22
27,deletion,last_layer,white-5,0,0.402,0.096,73
28,deletion,last_layer,white-5,1,0.428,0.136,21
29,deletion,last_layer,white-5,2,0.267,0.131,22
30,deletion,slice_weighted_rollout,attention_mask,0,0.563,0.073,73
31,deletion,slice_weighted_rollout,attention_mask,1,0.460,0.075,21
32,deletion,slice_weighted_rollout,attention_mask,2,0.221,0.153,22
33,deletion,slice_weighted_rollout,black-5,0,0.475,0.132,73
34,deletion,slice_weighted_rollout,black-5,1,0.218,0.082,21
35,deletion,slice_weighted_rollout,black-5,2,0.122,0.037,22
36,deletion,slice_weighted_rollout,gaussian_blur,0,0.639,0.150,73
37,deletion,slice_weighted_rollout,gaussian_blur,1,0.200,0.072,21
38,deletion,slice_weighted_rollout,gaussian_blur,2,0.233,0.110,22
39,deletion,slice_weighted_rollout,minimum-intensity,0,0.622,0.105,73
40,deletion,slice_weighted_rollout,minimum-intensity,1,0.278,0.114,21
41,deletion,slice_weighted_rollout,minimum-intensity,2,0.224,0.087,22
42,deletion,slice_weighted_rollout,white-5,0,0.436,0.127,73
43,deletion,slice_weighted_rollout,white-5,1,0.341,0.131,21
44,deletion,slice_weighted_rollout,white-5,2,0.299,0.162,22
45,insertion,gradcam,attention_mask,0,0.849,0.049,73
46,insertion,gradcam,attention_mask,1,0.632,0.108,21
47,insertion,gradcam,attention_mask,2,0.771,0.102,22
48,insertion,gradcam,black-5,0,0.580,0.118,73
49,insertion,gradcam,black-5,1,0.440,0.118,21
50,insertion,gradcam,black-5,2,0.440,0.160,22
51,insertion,gradcam,gaussian_blur,0,0.663,0.105,73
52,insertion,gradcam,gaussian_blur,1,0.534,0.100,21
53,insertion,gradcam,gaussian_blur,2,0.689,0.112,22
54,insertion,gradcam,minimum-intensity,0,0.830,0.058,73
55,insertion,gradcam,minimum-intensity,1,0.706,0.084,21
56,insertion,gradcam,minimum-intensity,2,0.714,0.147,22
57,insertion,gradcam,white-5,0,0.630,0.123,73
58,insertion,gradcam,white-5,1,0.720,0.109,21
59,insertion,gradcam,white-5,2,0.764,0.110,22
60,insertion,last_layer,attention_mask,0,0.806,0.085,73
61,insertion,last_layer,attention_mask,1,0.519,0.168,21
62,insertion,last_layer,attention_mask,2,0.846,0.081,22
63,insertion,last_layer,black-5,0,0.569,0.142,73
64,insertion,last_layer,black-5,1,0.308,0.095,21
65,insertion,last_layer,black-5,2,0.543,0.212,22
66,insertion,last_layer,gaussian_blur,0,0.531,0.133,73
67,insertion,last_layer,gaussian_blur,1,0.493,0.125,21
68,insertion,last_layer,gaussian_blur,2,0.769,0.136,22
69,insertion,last_layer,minimum-intensity,0,0.816,0.084,73
70,insertion,last_layer,minimum-intensity,1,0.550,0.126,21
71,insertion,last_layer,minimum-intensity,2,0.741,0.179,22
72,insertion,last_layer,white-5,0,0.434,0.136,73
73,insertion,last_layer,white-5,1,0.575,0.175,21
74,insertion,last_layer,white-5,2,0.805,0.135,22
75,insertion,slice_weighted_rollout,attention_mask,0,0.823,0.106,73
76,insertion,slice_weighted_rollout,attention_mask,1,0.624,0.118,21
77,insertion,slice_weighted_rollout,attention_mask,2,0.854,0.055,22
78,insertion,slice_weighted_rollout,black-5,0,0.549,0.109,73
79,insertion,slice_weighted_rollout,black-5,1,0.476,0.098,21
80,insertion,slice_weighted_rollout,black-5,2,0.803,0.086,22
81,insertion,slice_weighted_rollout,gaussian_blur,0,0.518,0.169,73
82,insertion,slice_weighted_rollout,gaussian_blur,1,0.564,0.087,21
83,insertion,slice_weighted_rollout,gaussian_blur,2,0.826,0.103,22
84,insertion,slice_weighted_rollout,minimum-intensity,0,0.790,0.130,73
85,insertion,slice_weighted_rollout,minimum-intensity,1,0.627,0.090,21
86,insertion,slice_weighted_rollout,minimum-intensity,2,0.787,0.132,22
87,insertion,slice_weighted_rollout,white-5,0,0.491,0.144,73
88,insertion,slice_weighted_rollout,white-5,1,0.637,0.125,21
89,insertion,slice_weighted_rollout,white-5,2,0.820,0.093,22
90,negative,gradcam,attention_mask,0,0.849,0.049,73
91,negative,gradcam,attention_mask,1,0.629,0.108,21
92,negative,gradcam,attention_mask,2,0.774,0.096,22
93,negative,gradcam,black-5,0,0.580,0.116,73
94,negative,gradcam,black-5,1,0.441,0.118,21
95,negative,gradcam,black-5,2,0.443,0.147,22
96,negative,gradcam,gaussian_blur,0,0.663,0.104,73
97,negative,gradcam,gaussian_blur,1,0.534,0.099,21
98,negative,gradcam,gaussian_blur,2,0.684,0.115,22
99,negative,gradcam,minimum-intensity,0,0.829,0.059,73
100,negative,gradcam,minimum-intensity,1,0.702,0.079,21
101,negative,gradcam,minimum-intensity,2,0.716,0.146,22
102,negative,gradcam,white-5,0,0.630,0.125,73
103,negative,gradcam,white-5,1,0.719,0.109,21
104,negative,gradcam,white-5,2,0.759,0.124,22
105,negative,last_layer,attention_mask,0,0.807,0.085,73
106,negative,last_layer,attention_mask,1,0.521,0.168,21
107,negative,last_layer,attention_mask,2,0.845,0.081,22
108,negative,last_layer,black-5,0,0.570,0.142,73
109,negative,last_layer,black-5,1,0.309,0.095,21
110,negative,last_layer,black-5,2,0.544,0.212,22
111,negative,last_layer,gaussian_blur,0,0.531,0.133,73
112,negative,last_layer,gaussian_blur,1,0.493,0.125,21
113,negative,last_layer,gaussian_blur,2,0.769,0.136,22
114,negative,last_layer,minimum-intensity,0,0.816,0.084,73
115,negative,last_layer,minimum-intensity,1,0.551,0.125,21
116,negative,last_layer,minimum-intensity,2,0.740,0.180,22
117,negative,last_layer,white-5,0,0.435,0.137,73
118,negative,last_layer,white-5,1,0.575,0.174,21
119,negative,last_layer,white-5,2,0.805,0.135,22
120,negative,slice_weighted_rollout,attention_mask,0,0.823,0.107,73
121,negative,slice_weighted_rollout,attention_mask,1,0.625,0.116,21
122,negative,slice_weighted_rollout,attention_mask,2,0.854,0.056,22
123,negative,slice_weighted_rollout,black-5,0,0.549,0.109,73
124,negative,slice_weighted_rollout,black-5,1,0.476,0.098,21
125,negative,slice_weighted_rollout,black-5,2,0.803,0.086,22
126,negative,slice_weighted_rollout,gaussian_blur,0,0.519,0.169,73
127,negative,slice_weighted_rollout,gaussian_blur,1,0.563,0.086,21
128,negative,slice_weighted_rollout,gaussian_blur,2,0.827,0.103,22
129,negative,slice_weighted_rollout,minimum-intensity,0,0.791,0.128,73
130,negative,slice_weighted_rollout,minimum-intensity,1,0.627,0.091,21
131,negative,slice_weighted_rollout,minimum-intensity,2,0.788,0.131,22
132,negative,slice_weighted_rollout,white-5,0,0.492,0.144,73
133,negative,slice_weighted_rollout,white-5,1,0.637,0.125,21
134,negative,slice_weighted_rollout,white-5,2,0.821,0.094,22

In [4]:
class_summary[class_summary["mode"] == 'deletion']

,mode,xai_method,replacement,predicted_class,mean,std,count
0,deletion,gradcam,attention_mask,0,0.527,0.150,73
1,deletion,gradcam,attention_mask,1,0.382,0.064,21
2,deletion,gradcam,attention_mask,2,0.136,0.056,22
3,deletion,gradcam,black-5,0,0.376,0.146,73
4,deletion,gradcam,black-5,1,0.264,0.063,21
5,deletion,gradcam,black-5,2,0.162,0.054,22
6,deletion,gradcam,gaussian_blur,0,0.541,0.126,73
7,deletion,gradcam,gaussian_blur,1,0.177,0.038,21
8,deletion,gradcam,gaussian_blur,2,0.231,0.099,22
9,deletion,gradcam,minimum-intensity,0,0.599,0.155,73
10,deletion,gradcam,minimum-intensity,1,0.205,0.060,21
11,deletion,gradcam,minimum-intensity,2,0.164,0.056,22
12,deletion,gradcam,white-5,0,0.348,0.089,73
13,deletion,gradcam,white-5,1,0.229,0.070,21
14,deletion,gradcam,white-5,2,0.159,0.105,22
15,deletion,last_layer,attention_mask,0,0.658,0.101,73
16,deletion,last_layer,attention_mask,1,0.416,0.104,21
17,deletion,last_layer,attention_mask,2,0.233,0.163,22
18,deletion,last_layer,black-5,0,0.391,0.137,73
19,deletion,last_layer,black-5,1,0.223,0.073,21
20,deletion,last_layer,black-5,2,0.182,0.083,22
21,deletion,last_layer,gaussian_blur,0,0.609,0.136,73
22,deletion,last_layer,gaussian_blur,1,0.187,0.062,21
23,deletion,last_layer,gaussian_blur,2,0.259,0.126,22
24,deletion,last_layer,minimum-intensity,0,0.579,0.118,73
25,deletion,last_layer,minimum-intensity,1,0.280,0.090,21
26,deletion,last_layer,minimum-intensity,2,0.212,0.093,22
27,deletion,last_layer,white-5,0,0.402,0.096,73
28,deletion,last_layer,white-5,1,0.428,0.136,21
29,deletion,last_layer,white-5,2,0.267,0.131,22
30,deletion,slice_weighted_rollout,attention_mask,0,0.563,0.073,73
31,deletion,slice_weighted_rollout,attention_mask,1,0.460,0.075,21
32,deletion,slice_weighted_rollout,attention_mask,2,0.221,0.153,22
33,deletion,slice_weighted_rollout,black-5,0,0.475,0.132,73
34,deletion,slice_weighted_rollout,black-5,1,0.218,0.082,21
35,deletion,slice_weighted_rollout,black-5,2,0.122,0.037,22
36,deletion,slice_weighted_rollout,gaussian_blur,0,0.639,0.150,73
37,deletion,slice_weighted_rollout,gaussian_blur,1,0.200,0.072,21
38,deletion,slice_weighted_rollout,gaussian_blur,2,0.233,0.110,22
39,deletion,slice_weighted_rollout,minimum-intensity,0,0.622,0.105,73
40,deletion,slice_weighted_rollout,minimum-intensity,1,0.278,0.114,21
41,deletion,slice_weighted_rollout,minimum-intensity,2,0.224,0.087,22
42,deletion,slice_weighted_rollout,white-5,0,0.436,0.127,73
43,deletion,slice_weighted_rollout,white-5,1,0.341,0.131,21
44,deletion,slice_weighted_rollout,white-5,2,0.299,0.162,22

## Macro Average

In [5]:
macro_summary = (
    class_summary
    .groupby(["mode", "xai_method", "replacement"])["mean"]
    .mean()
    .reset_index(name="macro_mean_auc")
)

print("=== Macro-average (class-balanced) ===")
macro_summary

=== Macro-average (class-balanced) ===

         mode              xai_method        replacement  macro_mean_auc
0    deletion                 gradcam     attention_mask        0.348333
1    deletion                 gradcam            black-5        0.267333
2    deletion                 gradcam      gaussian_blur        0.316333
3    deletion                 gradcam  minimum-intensity        0.322667
4    deletion                 gradcam            white-5        0.245333
5    deletion              last_layer     attention_mask        0.435667
6    deletion              last_layer            black-5        0.265333
7    deletion              last_layer      gaussian_blur        0.351667
8    deletion              last_layer  minimum-intensity        0.357000
9    deletion              last_layer            white-5        0.365667
10   deletion  slice_weighted_rollout     attention_mask        0.414667
11   deletion  slice_weighted_rollout            black-5        0.271667
12   deletion  slice_weighted_rollout      gaussian_blur        0.357333
13   deletion  slice_weighted_rollout  minimum-intensity        0.374667
14   deletion  slice_weighted_rollout            white-5        0.358667
15  insertion                 gradcam     attention_mask        0.750667
16  insertion                 gradcam            black-5        0.486667
17  insertion                 gradcam      gaussian_blur        0.628667
18  insertion                 gradcam  minimum-intensity        0.750000
19  insertion                 gradcam            white-5        0.704667
20  insertion              last_layer     attention_mask        0.723667
21  insertion              last_layer            black-5        0.473333
22  insertion              last_layer      gaussian_blur        0.597667
23  insertion              last_layer  minimum-intensity        0.702333
24  insertion              last_layer            white-5        0.604667
25  insertion  slice_weighted_rollout     attention_mask        0.767000
26  insertion  slice_weighted_rollout            black-5        0.609333
27  insertion  slice_weighted_rollout      gaussian_blur        0.636000
28  insertion  slice_weighted_rollout  minimum-intensity        0.734667
29  insertion  slice_weighted_rollout            white-5        0.649333
30   negative                 gradcam     attention_mask        0.750667
31   negative                 gradcam            black-5        0.488000
32   negative                 gradcam      gaussian_blur        0.627000
33   negative                 gradcam  minimum-intensity        0.749000
34   negative                 gradcam            white-5        0.702667
35   negative              last_layer     attention_mask        0.724333
36   negative              last_layer            black-5        0.474333
37   negative              last_layer      gaussian_blur        0.597667
38   negative              last_layer  minimum-intensity        0.702333
39   negative              last_layer            white-5        0.605000
40   negative  slice_weighted_rollout     attention_mask        0.767333
41   negative  slice_weighted_rollout            black-5        0.609333
42   negative  slice_weighted_rollout      gaussian_blur        0.636333
43   negative  slice_weighted_rollout  minimum-intensity        0.735333
44   negative  slice_weighted_rollout            white-5        0.650000

In [6]:
macro_summary = (
    df_all
    .groupby(["mode", "xai_method", "replacement", "predicted_class"])["auc"]
    .mean()
    .groupby(["mode", "xai_method", "replacement"])
    .agg(macro_mean_auc="mean", macro_std_auc="std", count="count")
    .reset_index()
)
macro_summary["macro_mean_auc"] = macro_summary["macro_mean_auc"].round(3)
macro_summary["macro_std_auc"] = macro_summary["macro_std_auc"].round(3)
print("=== Macro-average (class-balanced) ===")
macro_summary

=== Macro-average (class-balanced) ===

,mode,xai_method,replacement,macro_mean_auc,macro_std_auc,count
0,deletion,gradcam,attention_mask,0.348,0.198,3
1,deletion,gradcam,black-5,0.267,0.107,3
2,deletion,gradcam,gaussian_blur,0.316,0.196,3
3,deletion,gradcam,minimum-intensity,0.323,0.240,3
4,deletion,gradcam,white-5,0.245,0.095,3
5,deletion,last_layer,attention_mask,0.436,0.213,3
6,deletion,last_layer,black-5,0.266,0.111,3
7,deletion,last_layer,gaussian_blur,0.351,0.226,3
8,deletion,last_layer,minimum-intensity,0.357,0.195,3
9,deletion,last_layer,white-5,0.366,0.086,3
10,deletion,slice_weighted_rollout,attention_mask,0.415,0.175,3
11,deletion,slice_weighted_rollout,black-5,0.272,0.182,3
12,deletion,slice_weighted_rollout,gaussian_blur,0.357,0.245,3
13,deletion,slice_weighted_rollout,minimum-intensity,0.375,0.216,3
14,deletion,slice_weighted_rollout,white-5,0.359,0.070,3
15,insertion,gradcam,attention_mask,0.751,0.110,3
16,insertion,gradcam,black-5,0.487,0.081,3
17,insertion,gradcam,gaussian_blur,0.629,0.083,3
18,insertion,gradcam,minimum-intensity,0.750,0.069,3
19,insertion,gradcam,white-5,0.705,0.068,3
20,insertion,last_layer,attention_mask,0.724,0.178,3
21,insertion,last_layer,black-5,0.474,0.144,3
22,insertion,last_layer,gaussian_blur,0.598,0.150,3
23,insertion,last_layer,minimum-intensity,0.702,0.137,3
24,insertion,last_layer,white-5,0.605,0.187,3
25,insertion,slice_weighted_rollout,attention_mask,0.767,0.125,3
26,insertion,slice_weighted_rollout,black-5,0.609,0.171,3
27,insertion,slice_weighted_rollout,gaussian_blur,0.636,0.166,3
28,insertion,slice_weighted_rollout,minimum-intensity,0.735,0.093,3
29,insertion,slice_weighted_rollout,white-5,0.650,0.165,3
30,negative,gradcam,attention_mask,0.751,0.112,3
31,negative,gradcam,black-5,0.488,0.080,3
32,negative,gradcam,gaussian_blur,0.627,0.081,3
33,negative,gradcam,minimum-intensity,0.749,0.069,3
34,negative,gradcam,white-5,0.703,0.066,3
35,negative,last_layer,attention_mask,0.724,0.177,3
36,negative,last_layer,black-5,0.474,0.144,3
37,negative,last_layer,gaussian_blur,0.598,0.150,3
38,negative,last_layer,minimum-intensity,0.703,0.136,3
39,negative,last_layer,white-5,0.605,0.187,3
40,negative,slice_weighted_rollout,attention_mask,0.767,0.124,3
41,negative,slice_weighted_rollout,black-5,0.609,0.172,3
42,negative,slice_weighted_rollout,gaussian_blur,0.636,0.167,3
43,negative,slice_weighted_rollout,minimum-intensity,0.735,0.094,3
44,negative,slice_weighted_rollout,white-5,0.650,0.165,3

## Combine Micro and Macro average

In [7]:
replacement_order = [
    "black-5",
    "minimum-intensity",
    "white-5",
    "gaussian_blur",
    "attention_mask"
]

In [8]:
combined_summary = (
    micro_summary
    .rename(columns={"mean": "micro_mean_auc", "std": "micro_std_auc"})
    .merge(macro_summary, on=["mode", "xai_method", "replacement"])
)

print("=== Combined Summary ===")
combined_summary

=== Combined Summary ===

,mode,xai_method,replacement,micro_mean_auc,micro_std_auc,count_x,macro_mean_auc,macro_std_auc,count_y
0,deletion,gradcam,attention_mask,0.426,0.196,116,0.348,0.198,3
1,deletion,gradcam,black-5,0.315,0.148,116,0.267,0.107,3
2,deletion,gradcam,gaussian_blur,0.416,0.197,116,0.316,0.196,3
3,deletion,gradcam,minimum-intensity,0.445,0.239,116,0.323,0.240,3
4,deletion,gradcam,white-5,0.290,0.118,116,0.245,0.095,3
5,deletion,last_layer,attention_mask,0.533,0.207,116,0.436,0.213,3
6,deletion,last_layer,black-5,0.321,0.150,116,0.266,0.111,3
7,deletion,last_layer,gaussian_blur,0.466,0.225,116,0.351,0.226,3
8,deletion,last_layer,minimum-intensity,0.455,0.196,116,0.357,0.195,3
9,deletion,last_layer,white-5,0.381,0.124,116,0.366,0.086,3
10,deletion,slice_weighted_rollout,attention_mask,0.480,0.161,116,0.415,0.175,3
11,deletion,slice_weighted_rollout,black-5,0.361,0.188,116,0.272,0.182,3
12,deletion,slice_weighted_rollout,gaussian_blur,0.482,0.243,116,0.357,0.245,3
13,deletion,slice_weighted_rollout,minimum-intensity,0.484,0.208,116,0.375,0.216,3
14,deletion,slice_weighted_rollout,white-5,0.393,0.146,116,0.359,0.070,3
15,insertion,gradcam,attention_mask,0.795,0.111,116,0.751,0.110,3
16,insertion,gradcam,black-5,0.528,0.143,116,0.487,0.081,3
17,insertion,gradcam,gaussian_blur,0.644,0.117,116,0.629,0.083,3
18,insertion,gradcam,minimum-intensity,0.785,0.103,116,0.750,0.069,3
19,insertion,gradcam,white-5,0.672,0.130,116,0.705,0.068,3
20,insertion,last_layer,attention_mask,0.762,0.155,116,0.724,0.178,3
21,insertion,last_layer,black-5,0.517,0.179,116,0.474,0.144,3
22,insertion,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
23,insertion,last_layer,minimum-intensity,0.753,0.152,116,0.702,0.137,3
24,insertion,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
25,insertion,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.125,3
26,insertion,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.171,3
27,insertion,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.166,3
28,insertion,slice_weighted_rollout,minimum-intensity,0.760,0.138,116,0.735,0.093,3
29,insertion,slice_weighted_rollout,white-5,0.580,0.184,116,0.650,0.165,3
30,negative,gradcam,attention_mask,0.795,0.110,116,0.751,0.112,3
31,negative,gradcam,black-5,0.529,0.139,116,0.488,0.080,3
32,negative,gradcam,gaussian_blur,0.643,0.117,116,0.627,0.081,3
33,negative,gradcam,minimum-intensity,0.784,0.103,116,0.749,0.069,3
34,negative,gradcam,white-5,0.671,0.133,116,0.703,0.066,3
35,negative,last_layer,attention_mask,0.762,0.155,116,0.724,0.177,3
36,negative,last_layer,black-5,0.517,0.180,116,0.474,0.144,3
37,negative,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
38,negative,last_layer,minimum-intensity,0.754,0.151,116,0.703,0.136,3
39,negative,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
40,negative,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.124,3
41,negative,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.172,3
42,negative,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.167,3
43,negative,slice_weighted_rollout,minimum-intensity,0.761,0.137,116,0.735,0.094,3
44,negative,slice_weighted_rollout,white-5,0.581,0.184,116,0.650,0.165,3

In [9]:
combined_summary["replacement"] = pd.Categorical(
    combined_summary["replacement"],
    categories=replacement_order,
    ordered=True
)

In [10]:
combined_summary = combined_summary.sort_values(
    by=["mode", "xai_method", "replacement"]
).reset_index(drop=True)

In [11]:
combined_summary

,mode,xai_method,replacement,micro_mean_auc,micro_std_auc,count_x,macro_mean_auc,macro_std_auc,count_y
0,deletion,gradcam,black-5,0.315,0.148,116,0.267,0.107,3
1,deletion,gradcam,minimum-intensity,0.445,0.239,116,0.323,0.240,3
2,deletion,gradcam,white-5,0.290,0.118,116,0.245,0.095,3
3,deletion,gradcam,gaussian_blur,0.416,0.197,116,0.316,0.196,3
4,deletion,gradcam,attention_mask,0.426,0.196,116,0.348,0.198,3
5,deletion,last_layer,black-5,0.321,0.150,116,0.266,0.111,3
6,deletion,last_layer,minimum-intensity,0.455,0.196,116,0.357,0.195,3
7,deletion,last_layer,white-5,0.381,0.124,116,0.366,0.086,3
8,deletion,last_layer,gaussian_blur,0.466,0.225,116,0.351,0.226,3
9,deletion,last_layer,attention_mask,0.533,0.207,116,0.436,0.213,3
10,deletion,slice_weighted_rollout,black-5,0.361,0.188,116,0.272,0.182,3
11,deletion,slice_weighted_rollout,minimum-intensity,0.484,0.208,116,0.375,0.216,3
12,deletion,slice_weighted_rollout,white-5,0.393,0.146,116,0.359,0.070,3
13,deletion,slice_weighted_rollout,gaussian_blur,0.482,0.243,116,0.357,0.245,3
14,deletion,slice_weighted_rollout,attention_mask,0.480,0.161,116,0.415,0.175,3
15,insertion,gradcam,black-5,0.528,0.143,116,0.487,0.081,3
16,insertion,gradcam,minimum-intensity,0.785,0.103,116,0.750,0.069,3
17,insertion,gradcam,white-5,0.672,0.130,116,0.705,0.068,3
18,insertion,gradcam,gaussian_blur,0.644,0.117,116,0.629,0.083,3
19,insertion,gradcam,attention_mask,0.795,0.111,116,0.751,0.110,3
20,insertion,last_layer,black-5,0.517,0.179,116,0.474,0.144,3
21,insertion,last_layer,minimum-intensity,0.753,0.152,116,0.702,0.137,3
22,insertion,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
23,insertion,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
24,insertion,last_layer,attention_mask,0.762,0.155,116,0.724,0.178,3
25,insertion,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.171,3
26,insertion,slice_weighted_rollout,minimum-intensity,0.760,0.138,116,0.735,0.093,3
27,insertion,slice_weighted_rollout,white-5,0.580,0.184,116,0.650,0.165,3
28,insertion,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.166,3
29,insertion,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.125,3
30,negative,gradcam,black-5,0.529,0.139,116,0.488,0.080,3
31,negative,gradcam,minimum-intensity,0.784,0.103,116,0.749,0.069,3
32,negative,gradcam,white-5,0.671,0.133,116,0.703,0.066,3
33,negative,gradcam,gaussian_blur,0.643,0.117,116,0.627,0.081,3
34,negative,gradcam,attention_mask,0.795,0.110,116,0.751,0.112,3
35,negative,last_layer,black-5,0.517,0.180,116,0.474,0.144,3
36,negative,last_layer,minimum-intensity,0.754,0.151,116,0.703,0.136,3
37,negative,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
38,negative,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
39,negative,last_layer,attention_mask,0.762,0.155,116,0.724,0.177,3
40,negative,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.172,3
41,negative,slice_weighted_rollout,minimum-intensity,0.761,0.137,116,0.735,0.094,3
42,negative,slice_weighted_rollout,white-5,0.581,0.184,116,0.650,0.165,3
43,negative,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.167,3
44,negative,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.124,3

## Method Comparison

In [12]:
method_summary = (
    df_all.groupby(["mode", "xai_method"])["auc"]
    .agg(["mean", "std"])
    .reset_index()
)

print("=== Method comparison ===")
method_summary

=== Method comparison ===

        mode              xai_method      mean       std
0   deletion                 gradcam  0.378708  0.194210
1   deletion              last_layer  0.431473  0.197616
2   deletion  slice_weighted_rollout  0.440078  0.198635
3  insertion                 gradcam  0.684960  0.156245
4  insertion              last_layer  0.626326  0.202442
5  insertion  slice_weighted_rollout  0.660452  0.185519
6   negative                 gradcam  0.684435  0.155632
7   negative              last_layer  0.626569  0.202453
8   negative  slice_weighted_rollout  0.660632  0.185369

## Strategy Comparison

In [13]:
strategy_summary = (
    df_all.groupby(["mode", "replacement"])["auc"]
    .agg(["mean", "std"])
    .reset_index()
)

print("=== Strategy comparison ===")
strategy_summary

=== Strategy comparison ===

         mode        replacement      mean       std
0    deletion     attention_mask  0.479791  0.193240
1    deletion            black-5  0.332617  0.163709
2    deletion      gaussian_blur  0.454955  0.223714
3    deletion  minimum-intensity  0.461478  0.214988
4    deletion            white-5  0.354923  0.137202
5   insertion     attention_mask  0.783256  0.133269
6   insertion            black-5  0.543121  0.160622
7   insertion      gaussian_blur  0.599535  0.161606
8   insertion  minimum-intensity  0.766245  0.132824
9   insertion            white-5  0.594073  0.184072
10   negative     attention_mask  0.783350  0.132827
11   negative            black-5  0.543331  0.159406
12   negative      gaussian_blur  0.599293  0.161487
13   negative  minimum-intensity  0.766213  0.132379
14   negative            white-5  0.593874  0.184521

## Best Method

In [14]:
# For deletion → lower is better
best_deletion = micro_summary[micro_summary["mode"] == "deletion"].sort_values("mean")

# For insertion → higher is better
best_insertion = micro_summary[micro_summary["mode"] == "insertion"].sort_values("mean", ascending=False)

print("=== Best (Deletion) ===")
print(best_deletion.head())

print("\n=== Best (Insertion) ===")
print(best_insertion.head())

=== Best (Deletion) ===
        mode              xai_method replacement   mean    std  count
4   deletion                 gradcam     white-5  0.290  0.118    116
1   deletion                 gradcam     black-5  0.315  0.148    116
6   deletion              last_layer     black-5  0.321  0.150    116
11  deletion  slice_weighted_rollout     black-5  0.361  0.188    116
9   deletion              last_layer     white-5  0.381  0.124    116

=== Best (Insertion) ===
         mode              xai_method        replacement   mean    std  count
15  insertion                 gradcam     attention_mask  0.795  0.111    116
25  insertion  slice_weighted_rollout     attention_mask  0.793  0.129    116
18  insertion                 gradcam  minimum-intensity  0.785  0.103    116
20  insertion              last_layer     attention_mask  0.762  0.155    116
28  insertion  slice_weighted_rollout  minimum-intensity  0.760  0.138    116

## Save Everythings

In [15]:
micro_summary.to_csv("micro_summary.csv", index=False)
class_summary.to_csv("class_summary.csv", index=False)
macro_summary.to_csv("macro_summary.csv", index=False)
method_summary.to_csv("method_summary.csv", index=False)
strategy_summary.to_csv("strategy_summary.csv", index=False)

print("All results saved")

All results saved

# Calculate curve again without Normalized Confidence

In [16]:
evaluation_methods = {
    "deletion": "Deletion",
    "insertion": "Insertion",
    "negative": "Negative Perturbation",
}

replacement_strategies = {
    "black-5": "Black masking", 
    "minimum-intensity": "Minimum intensity",
    "white-5": "White masking", 
    "gaussian_blur": "Gaussian Blur",
    "attention_mask" : "Attention Mask",  
}

xai_methods = {
    "gradcam": "Grad-CAM",
    "last_layer": "Last-layer attention", 
    "slice_weighted_rollout": "Attention rollout" 
}

colors = {
    "gradcam": "#1f77b4",              # blue
    "last_layer": "#ff7f0e",           # orange
    "slice_weighted_rollout": "#2ca02c"  # green
}

In [17]:
import numpy as np
from pathlib import Path
base_path = Path("/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results")
test_data = np.load("/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results/deletion/deletion_curves/gradcam/attention_mask/02F4A1FB_left_curve_attention_mask.npy", allow_pickle=True).item()
test_data.keys()

dict_keys(['percentages', 'raw_logits', 'confidences', 'normalized_confidences', 'predicted_class', 'predicted_confidences', 'predicted_normalized_confidences', 'auc', 'replacement'])