# Perturbation Evaluation Metrics

## Load Files

In [9]:
import glob
import os
import pandas as pd

# Base directory
base_path = "/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results"

# Metrics to include
metrics = ["deletion", "insertion", "negative"]

# Collect all CSV files under:
# evaluation_results/{metric}/csv_files/absolute/*.csv
csv_files = []

for metric in metrics:
    metric_path = os.path.join(
        base_path,
        metric,
        "csv_files",
        "absolute",
        "*.csv"
    )
    
    files = glob.glob(metric_path)
    csv_files.extend(files)

print(f"Found {len(csv_files)} files")

# Load and combine
dfs = []

for file in csv_files:
    df = pd.read_csv(file)

    # Add metadata
    df["file_name"] = os.path.basename(file)
    df["metric"] = file.split(os.sep)[-4]  # deletion/insertion/negative

    dfs.append(df)

# Combine all dataframes
df_all = pd.concat(dfs, ignore_index=True)

# Preview
print(df_all.shape)
df_all.head()

Found 75 files
(8700, 10)

,UID,dataset,model,xai_method,mode,predicted_class,auc,replacement,file_name,metric
0,02F4A1FB_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.628240,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv,deletion
1,02F4A1FB_right,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.556623,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv,deletion
2,08FEB48B_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,2,0.416956,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv,deletion
3,1647533552_left,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.448901,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv,deletion
4,1647533552_right,ODELIA,DinoV2ClassifierSlice,slice_weighted_rollout,deletion,0,0.367227,gaussian_blur,deletion_slice_weighted_rollout_gaussian_blur.csv,deletion

## Micro Average

In [10]:
micro_summary = (
    df_all.groupby(["mode", "xai_method", "replacement"])["auc"]
    .agg(["mean", "std", "count"])
    .reset_index()
)
micro_summary["mean"] = micro_summary["mean"].round(3)
micro_summary["std"] = micro_summary["std"].round(3)
print("=== Micro-average (overall) ===")
micro_summary

=== Micro-average (overall) ===

         mode              xai_method        replacement   mean    std  count
0    deletion                grad_sam     attention_mask  0.419  0.178    116
1    deletion                grad_sam            black-5  0.293  0.133    116
2    deletion                grad_sam      gaussian_blur  0.473  0.238    116
3    deletion                grad_sam  minimum-intensity  0.406  0.181    116
4    deletion                grad_sam            white-5  0.314  0.114    116
5    deletion                 gradcam     attention_mask  0.426  0.196    116
6    deletion                 gradcam            black-5  0.315  0.148    116
7    deletion                 gradcam      gaussian_blur  0.416  0.197    116
8    deletion                 gradcam  minimum-intensity  0.445  0.239    116
9    deletion                 gradcam            white-5  0.290  0.118    116
10   deletion               hires_cam     attention_mask  0.572  0.223    116
11   deletion               hires_cam            black-5  0.390  0.197    116
12   deletion               hires_cam      gaussian_blur  0.488  0.244    116
13   deletion               hires_cam  minimum-intensity  0.549  0.267    116
14   deletion               hires_cam            white-5  0.402  0.155    116
15   deletion              last_layer     attention_mask  0.533  0.207    116
16   deletion              last_layer            black-5  0.321  0.150    116
17   deletion              last_layer      gaussian_blur  0.466  0.225    116
18   deletion              last_layer  minimum-intensity  0.455  0.196    116
19   deletion              last_layer            white-5  0.381  0.124    116
20   deletion  slice_weighted_rollout     attention_mask  0.480  0.161    116
21   deletion  slice_weighted_rollout            black-5  0.361  0.188    116
22   deletion  slice_weighted_rollout      gaussian_blur  0.482  0.243    116
23   deletion  slice_weighted_rollout  minimum-intensity  0.484  0.208    116
24   deletion  slice_weighted_rollout            white-5  0.393  0.146    116
25  insertion                grad_sam     attention_mask  0.789  0.155    116
26  insertion                grad_sam            black-5  0.564  0.184    116
27  insertion                grad_sam      gaussian_blur  0.584  0.170    116
28  insertion                grad_sam  minimum-intensity  0.757  0.143    116
29  insertion                grad_sam            white-5  0.564  0.204    116
30  insertion                 gradcam     attention_mask  0.795  0.111    116
31  insertion                 gradcam            black-5  0.528  0.143    116
32  insertion                 gradcam      gaussian_blur  0.644  0.117    116
33  insertion                 gradcam  minimum-intensity  0.785  0.103    116
34  insertion                 gradcam            white-5  0.672  0.130    116
35  insertion               hires_cam     attention_mask  0.764  0.147    116
36  insertion               hires_cam            black-5  0.501  0.170    116
37  insertion               hires_cam      gaussian_blur  0.618  0.149    116
38  insertion               hires_cam  minimum-intensity  0.747  0.170    116
39  insertion               hires_cam            white-5  0.550  0.206    116
40  insertion              last_layer     attention_mask  0.762  0.155    116
41  insertion              last_layer            black-5  0.517  0.179    116
42  insertion              last_layer      gaussian_blur  0.569  0.164    116
43  insertion              last_layer  minimum-intensity  0.753  0.152    116
44  insertion              last_layer            white-5  0.530  0.202    116
45  insertion  slice_weighted_rollout     attention_mask  0.793  0.129    116
46  insertion  slice_weighted_rollout            black-5  0.584  0.150    116
47  insertion  slice_weighted_rollout      gaussian_blur  0.585  0.188    116
48  insertion  slice_weighted_rollout  minimum-intensity  0.760  0.138    116
49  insertion  slice_weighted_rollout            white-5  0.580  0.184    116
50   negative                grad_sam     attention_mask  0.788  0.156    116
51   negative                grad_sam            black-5  0.564  0.184    116
52   negative                grad_sam      gaussian_blur  0.584  0.169    116
53   negative                grad_sam  minimum-intensity  0.757  0.143    116
54   negative                grad_sam            white-5  0.565  0.204    116
55   negative                 gradcam     attention_mask  0.795  0.110    116
56   negative                 gradcam            black-5  0.529  0.139    116
57   negative                 gradcam      gaussian_blur  0.643  0.117    116
58   negative                 gradcam  minimum-intensity  0.784  0.103    116
59   negative                 gradcam            white-5  0.671  0.133    116
60   negative               hires_cam     attention_mask  0.763  0.148    116
61   negative               hires_cam            black-5  0.500  0.169    116
62   negative               hires_cam      gaussian_blur  0.616  0.150    116
63   negative               hires_cam  minimum-intensity  0.748  0.171    116
64   negative               hires_cam            white-5  0.547  0.207    116
65   negative              last_layer     attention_mask  0.762  0.155    116
66   negative              last_layer            black-5  0.517  0.180    116
67   negative              last_layer      gaussian_blur  0.569  0.164    116
68   negative              last_layer  minimum-intensity  0.754  0.151    116
69   negative              last_layer            white-5  0.530  0.202    116
70   negative  slice_weighted_rollout     attention_mask  0.793  0.129    116
71   negative  slice_weighted_rollout            black-5  0.584  0.150    116
72   negative  slice_weighted_rollout      gaussian_blur  0.585  0.188    116
73   negative  slice_weighted_rollout  minimum-intensity  0.761  0.137    116
74   negative  slice_weighted_rollout            white-5  0.581  0.184    116

## Class-wise

In [11]:
class_summary = (
    df_all.groupby(["mode", "xai_method", "replacement", "predicted_class"])["auc"]
    .agg(["mean", "std", "count"])
    .reset_index()
)

class_summary["mean"] = class_summary["mean"].round(3)
class_summary["std"] = class_summary["std"].round(3)

print("=== Class-wise (macro view) ===")
# Source - https://stackoverflow.com/a/16433953
# Posted by Wouter Overmeire, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-25, License - CC BY-SA 4.0

pd.set_option('display.max_rows', 500)

class_summary

=== Class-wise (macro view) ===

,mode,xai_method,replacement,predicted_class,mean,std,count
0,deletion,grad_sam,attention_mask,0,0.514,0.108,73
1,deletion,grad_sam,attention_mask,1,0.386,0.099,21
2,deletion,grad_sam,attention_mask,2,0.134,0.075,22
3,deletion,grad_sam,black-5,0,0.349,0.127,73
4,deletion,grad_sam,black-5,1,0.210,0.082,21
5,deletion,grad_sam,black-5,2,0.184,0.072,22
6,deletion,grad_sam,gaussian_blur,0,0.620,0.149,73
7,deletion,grad_sam,gaussian_blur,1,0.167,0.055,21
8,deletion,grad_sam,gaussian_blur,2,0.280,0.158,22
9,deletion,grad_sam,minimum-intensity,0,0.518,0.115,73
10,deletion,grad_sam,minimum-intensity,1,0.222,0.089,21
11,deletion,grad_sam,minimum-intensity,2,0.206,0.080,22
12,deletion,grad_sam,white-5,0,0.347,0.080,73
13,deletion,grad_sam,white-5,1,0.352,0.125,21
14,deletion,grad_sam,white-5,2,0.171,0.091,22
15,deletion,gradcam,attention_mask,0,0.527,0.150,73
16,deletion,gradcam,attention_mask,1,0.382,0.064,21
17,deletion,gradcam,attention_mask,2,0.136,0.056,22
18,deletion,gradcam,black-5,0,0.376,0.146,73
19,deletion,gradcam,black-5,1,0.264,0.063,21
20,deletion,gradcam,black-5,2,0.162,0.054,22
21,deletion,gradcam,gaussian_blur,0,0.541,0.126,73
22,deletion,gradcam,gaussian_blur,1,0.177,0.038,21
23,deletion,gradcam,gaussian_blur,2,0.231,0.099,22
24,deletion,gradcam,minimum-intensity,0,0.599,0.155,73
25,deletion,gradcam,minimum-intensity,1,0.205,0.060,21
26,deletion,gradcam,minimum-intensity,2,0.164,0.056,22
27,deletion,gradcam,white-5,0,0.348,0.089,73
28,deletion,gradcam,white-5,1,0.229,0.070,21
29,deletion,gradcam,white-5,2,0.159,0.105,22
30,deletion,hires_cam,attention_mask,0,0.721,0.082,73
31,deletion,hires_cam,attention_mask,1,0.393,0.070,21
32,deletion,hires_cam,attention_mask,2,0.251,0.166,22
33,deletion,hires_cam,black-5,0,0.509,0.137,73
34,deletion,hires_cam,black-5,1,0.212,0.089,21
35,deletion,hires_cam,black-5,2,0.167,0.083,22
36,deletion,hires_cam,gaussian_blur,0,0.660,0.096,73
37,deletion,hires_cam,gaussian_blur,1,0.168,0.049,21
38,deletion,hires_cam,gaussian_blur,2,0.221,0.108,22
39,deletion,hires_cam,minimum-intensity,0,0.741,0.087,73
40,deletion,hires_cam,minimum-intensity,1,0.247,0.101,21
41,deletion,hires_cam,minimum-intensity,2,0.202,0.103,22
42,deletion,hires_cam,white-5,0,0.450,0.136,73
43,deletion,hires_cam,white-5,1,0.361,0.148,21
44,deletion,hires_cam,white-5,2,0.280,0.148,22
45,deletion,last_layer,attention_mask,0,0.658,0.101,73
46,deletion,last_layer,attention_mask,1,0.416,0.104,21
47,deletion,last_layer,attention_mask,2,0.233,0.163,22
48,deletion,last_layer,black-5,0,0.391,0.137,73
49,deletion,last_layer,black-5,1,0.223,0.073,21
50,deletion,last_layer,black-5,2,0.182,0.083,22
51,deletion,last_layer,gaussian_blur,0,0.609,0.136,73
52,deletion,last_layer,gaussian_blur,1,0.187,0.062,21
53,deletion,last_layer,gaussian_blur,2,0.259,0.126,22
54,deletion,last_layer,minimum-intensity,0,0.579,0.118,73
55,deletion,last_layer,minimum-intensity,1,0.280,0.090,21
56,deletion,last_layer,minimum-intensity,2,0.212,0.093,22
57,deletion,last_layer,white-5,0,0.402,0.096,73
58,deletion,last_layer,white-5,1,0.428,0.136,21
59,deletion,last_layer,white-5,2,0.267,0.131,22
60,deletion,slice_weighted_rollout,attention_mask,0,0.563,0.073,73
61,deletion,slice_weighted_rollout,attention_mask,1,0.460,0.075,21
62,deletion,slice_weighted_rollout,attention_mask,2,0.221,0.153,22
63,deletion,slice_weighted_rollout,black-5,0,0.475,0.132,73
64,deletion,slice_weighted_rollout,black-5,1,0.218,0.082,21
65,deletion,slice_weighted_rollout,black-5,2,0.122,0.037,22
66,deletion,slice_weighted_rollout,gaussian_blur,0,0.639,0.150,73
67,deletion,slice_weighted_rollout,gaussian_blur,1,0.200,0.072,21
68,deletion,slice_weighted_rollout,gaussian_blur,2,0.233,0.110,22
69,deletion,slice_weighted_rollout,minimum-intensity,0,0.622,0.105,73
70,deletion,slice_weighted_rollout,minimum-intensity,1,0.278,0.114,21
71,deletion,slice_weighted_rollout,minimum-intensity,2,0.224,0.087,22
72,deletion,slice_weighted_rollout,white-5,0,0.436,0.127,73
73,deletion,slice_weighted_rollout,white-5,1,0.341,0.131,21
74,deletion,slice_weighted_rollout,white-5,2,0.299,0.162,22
75,insertion,grad_sam,attention_mask,0,0.851,0.065,73
76,insertion,grad_sam,attention_mask,1,0.520,0.159,21
77,insertion,grad_sam,attention_mask,2,0.839,0.072,22
78,insertion,grad_sam,black-5,0,0.591,0.143,73
79,insertion,grad_sam,black-5,1,0.349,0.100,21
80,insertion,grad_sam,black-5,2,0.681,0.205,22
81,insertion,grad_sam,gaussian_blur,0,0.537,0.138,73
82,insertion,grad_sam,gaussian_blur,1,0.524,0.143,21
83,insertion,grad_sam,gaussian_blur,2,0.799,0.119,22
84,insertion,grad_sam,minimum-intensity,0,0.812,0.084,73
85,insertion,grad_sam,minimum-intensity,1,0.597,0.149,21
86,insertion,grad_sam,minimum-intensity,2,0.727,0.174,22
87,insertion,grad_sam,white-5,0,0.471,0.161,73
88,insertion,grad_sam,white-5,1,0.606,0.164,21
89,insertion,grad_sam,white-5,2,0.835,0.076,22
90,insertion,gradcam,attention_mask,0,0.849,0.049,73
91,insertion,gradcam,attention_mask,1,0.632,0.108,21
92,insertion,gradcam,attention_mask,2,0.771,0.102,22
93,insertion,gradcam,black-5,0,0.580,0.118,73
94,insertion,gradcam,black-5,1,0.440,0.118,21
95,insertion,gradcam,black-5,2,0.440,0.160,22
96,insertion,gradcam,gaussian_blur,0,0.663,0.105,73
97,insertion,gradcam,gaussian_blur,1,0.534,0.100,21
98,insertion,gradcam,gaussian_blur,2,0.689,0.112,22
99,insertion,gradcam,minimum-intensity,0,0.830,0.058,73
100,insertion,gradcam,minimum-intensity,1,0.706,0.084,21
101,insertion,gradcam,minimum-intensity,2,0.714,0.147,22
102,insertion,gradcam,white-5,0,0.630,0.123,73
103,insertion,gradcam,white-5,1,0.720,0.109,21
104,insertion,gradcam,white-5,2,0.764,0.110,22
105,insertion,hires_cam,attention_mask,0,0.819,0.064,73
106,insertion,hires_cam,attention_mask,1,0.519,0.154,21
107,insertion,hires_cam,attention_mask,2,0.818,0.093,22
108,insertion,hires_cam,black-5,0,0.497,0.138,73
109,insertion,hires_cam,black-5,1,0.357,0.115,21
110,insertion,hires_cam,black-5,2,0.651,0.187,22
111,insertion,hires_cam,gaussian_blur,0,0.623,0.092,73
112,insertion,hires_cam,gaussian_blur,1,0.458,0.143,21
113,insertion,hires_cam,gaussian_blur,2,0.753,0.168,22
114,insertion,hires_cam,minimum-intensity,0,0.819,0.099,73
115,insertion,hires_cam,minimum-intensity,1,0.535,0.135,21
116,insertion,hires_cam,minimum-intensity,2,0.710,0.209,22
117,insertion,hires_cam,white-5,0,0.461,0.148,73
118,insertion,hires_cam,white-5,1,0.574,0.203,21
119,insertion,hires_cam,white-5,2,0.819,0.121,22
120,insertion,last_layer,attention_mask,0,0.806,0.085,73
121,insertion,last_layer,attention_mask,1,0.519,0.168,21
122,insertion,last_layer,attention_mask,2,0.846,0.081,22
123,insertion,last_layer,black-5,0,0.569,0.142,73
124,insertion,last_layer,black-5,1,0.308,0.095,21
125,insertion,last_layer,black-5,2,0.543,0.212,22
126,insertion,last_layer,gaussian_blur,0,0.531,0.133,73
127,insertion,last_layer,gaussian_blur,1,0.493,0.125,21
128,insertion,last_layer,gaussian_blur,2,0.769,0.136,22
129,insertion,last_layer,minimum-intensity,0,0.816,0.084,73
130,insertion,last_layer,minimum-intensity,1,0.550,0.126,21
131,insertion,last_layer,minimum-intensity,2,0.741,0.179,22
132,insertion,last_layer,white-5,0,0.434,0.136,73
133,insertion,last_layer,white-5,1,0.575,0.175,21
134,insertion,last_layer,white-5,2,0.805,0.135,22
135,insertion,slice_weighted_rollout,attention_mask,0,0.823,0.106,73
136,insertion,slice_weighted_rollout,attention_mask,1,0.624,0.118,21
137,insertion,slice_weighted_rollout,attention_mask,2,0.854,0.055,22
138,insertion,slice_weighted_rollout,black-5,0,0.549,0.109,73
139,insertion,slice_weighted_rollout,black-5,1,0.476,0.098,21
140,insertion,slice_weighted_rollout,black-5,2,0.803,0.086,22
141,insertion,slice_weighted_rollout,gaussian_blur,0,0.518,0.169,73
142,insertion,slice_weighted_rollout,gaussian_blur,1,0.564,0.087,21
143,insertion,slice_weighted_rollout,gaussian_blur,2,0.826,0.103,22
144,insertion,slice_weighted_rollout,minimum-intensity,0,0.790,0.130,73
145,insertion,slice_weighted_rollout,minimum-intensity,1,0.627,0.090,21
146,insertion,slice_weighted_rollout,minimum-intensity,2,0.787,0.132,22
147,insertion,slice_weighted_rollout,white-5,0,0.491,0.144,73
148,insertion,slice_weighted_rollout,white-5,1,0.637,0.125,21
149,insertion,slice_weighted_rollout,white-5,2,0.820,0.093,22
150,negative,grad_sam,attention_mask,0,0.851,0.065,73
151,negative,grad_sam,attention_mask,1,0.519,0.161,21
152,negative,grad_sam,attention_mask,2,0.838,0.073,22
153,negative,grad_sam,black-5,0,0.591,0.143,73
154,negative,grad_sam,black-5,1,0.349,0.100,21
155,negative,grad_sam,black-5,2,0.682,0.206,22
156,negative,grad_sam,gaussian_blur,0,0.536,0.135,73
157,negative,grad_sam,gaussian_blur,1,0.524,0.143,21
158,negative,grad_sam,gaussian_blur,2,0.799,0.120,22
159,negative,grad_sam,minimum-intensity,0,0.812,0.084,73
160,negative,grad_sam,minimum-intensity,1,0.597,0.149,21
161,negative,grad_sam,minimum-intensity,2,0.727,0.174,22
162,negative,grad_sam,white-5,0,0.471,0.161,73
163,negative,grad_sam,white-5,1,0.606,0.165,21
164,negative,grad_sam,white-5,2,0.835,0.076,22
165,negative,gradcam,attention_mask,0,0.849,0.049,73
166,negative,gradcam,attention_mask,1,0.629,0.108,21
167,negative,gradcam,attention_mask,2,0.774,0.096,22
168,negative,gradcam,black-5,0,0.580,0.116,73
169,negative,gradcam,black-5,1,0.441,0.118,21
170,negative,gradcam,black-5,2,0.443,0.147,22
171,negative,gradcam,gaussian_blur,0,0.663,0.104,73
172,negative,gradcam,gaussian_blur,1,0.534,0.099,21
173,negative,gradcam,gaussian_blur,2,0.684,0.115,22
174,negative,gradcam,minimum-intensity,0,0.829,0.059,73
175,negative,gradcam,minimum-intensity,1,0.702,0.079,21
176,negative,gradcam,minimum-intensity,2,0.716,0.146,22
177,negative,gradcam,white-5,0,0.630,0.125,73
178,negative,gradcam,white-5,1,0.719,0.109,21
179,negative,gradcam,white-5,2,0.759,0.124,22
180,negative,hires_cam,attention_mask,0,0.817,0.066,73
181,negative,hires_cam,attention_mask,1,0.518,0.154,21
182,negative,hires_cam,attention_mask,2,0.819,0.092,22
183,negative,hires_cam,black-5,0,0.495,0.138,73
184,negative,hires_cam,black-5,1,0.360,0.114,21
185,negative,hires_cam,black-5,2,0.653,0.188,22
186,negative,hires_cam,gaussian_blur,0,0.621,0.095,73
187,negative,hires_cam,gaussian_blur,1,0.458,0.143,21
188,negative,hires_cam,gaussian_blur,2,0.753,0.168,22
189,negative,hires_cam,minimum-intensity,0,0.819,0.100,73
190,negative,hires_cam,minimum-intensity,1,0.536,0.136,21
191,negative,hires_cam,minimum-intensity,2,0.711,0.210,22
192,negative,hires_cam,white-5,0,0.457,0.147,73
193,negative,hires_cam,white-5,1,0.576,0.203,21
194,negative,hires_cam,white-5,2,0.820,0.117,22
195,negative,last_layer,attention_mask,0,0.807,0.085,73
196,negative,last_layer,attention_mask,1,0.521,0.168,21
197,negative,last_layer,attention_mask,2,0.845,0.081,22
198,negative,last_layer,black-5,0,0.570,0.142,73
199,negative,last_layer,black-5,1,0.309,0.095,21
200,negative,last_layer,black-5,2,0.544,0.212,22
201,negative,last_layer,gaussian_blur,0,0.531,0.133,73
202,negative,last_layer,gaussian_blur,1,0.493,0.125,21
203,negative,last_layer,gaussian_blur,2,0.769,0.136,22
204,negative,last_layer,minimum-intensity,0,0.816,0.084,73
205,negative,last_layer,minimum-intensity,1,0.551,0.125,21
206,negative,last_layer,minimum-intensity,2,0.740,0.180,22
207,negative,last_layer,white-5,0,0.435,0.137,73
208,negative,last_layer,white-5,1,0.575,0.174,21
209,negative,last_layer,white-5,2,0.805,0.135,22
210,negative,slice_weighted_rollout,attention_mask,0,0.823,0.107,73
211,negative,slice_weighted_rollout,attention_mask,1,0.625,0.116,21
212,negative,slice_weighted_rollout,attention_mask,2,0.854,0.056,22
213,negative,slice_weighted_rollout,black-5,0,0.549,0.109,73
214,negative,slice_weighted_rollout,black-5,1,0.476,0.098,21
215,negative,slice_weighted_rollout,black-5,2,0.803,0.086,22
216,negative,slice_weighted_rollout,gaussian_blur,0,0.519,0.169,73
217,negative,slice_weighted_rollout,gaussian_blur,1,0.563,0.086,21
218,negative,slice_weighted_rollout,gaussian_blur,2,0.827,0.103,22
219,negative,slice_weighted_rollout,minimum-intensity,0,0.791,0.128,73
220,negative,slice_weighted_rollout,minimum-intensity,1,0.627,0.091,21
221,negative,slice_weighted_rollout,minimum-intensity,2,0.788,0.131,22
222,negative,slice_weighted_rollout,white-5,0,0.492,0.144,73
223,negative,slice_weighted_rollout,white-5,1,0.637,0.125,21
224,negative,slice_weighted_rollout,white-5,2,0.821,0.094,22

In [12]:
class_summary[class_summary["mode"] == 'deletion']

,mode,xai_method,replacement,predicted_class,mean,std,count
0,deletion,grad_sam,attention_mask,0,0.514,0.108,73
1,deletion,grad_sam,attention_mask,1,0.386,0.099,21
2,deletion,grad_sam,attention_mask,2,0.134,0.075,22
3,deletion,grad_sam,black-5,0,0.349,0.127,73
4,deletion,grad_sam,black-5,1,0.210,0.082,21
5,deletion,grad_sam,black-5,2,0.184,0.072,22
6,deletion,grad_sam,gaussian_blur,0,0.620,0.149,73
7,deletion,grad_sam,gaussian_blur,1,0.167,0.055,21
8,deletion,grad_sam,gaussian_blur,2,0.280,0.158,22
9,deletion,grad_sam,minimum-intensity,0,0.518,0.115,73
10,deletion,grad_sam,minimum-intensity,1,0.222,0.089,21
11,deletion,grad_sam,minimum-intensity,2,0.206,0.080,22
12,deletion,grad_sam,white-5,0,0.347,0.080,73
13,deletion,grad_sam,white-5,1,0.352,0.125,21
14,deletion,grad_sam,white-5,2,0.171,0.091,22
15,deletion,gradcam,attention_mask,0,0.527,0.150,73
16,deletion,gradcam,attention_mask,1,0.382,0.064,21
17,deletion,gradcam,attention_mask,2,0.136,0.056,22
18,deletion,gradcam,black-5,0,0.376,0.146,73
19,deletion,gradcam,black-5,1,0.264,0.063,21
20,deletion,gradcam,black-5,2,0.162,0.054,22
21,deletion,gradcam,gaussian_blur,0,0.541,0.126,73
22,deletion,gradcam,gaussian_blur,1,0.177,0.038,21
23,deletion,gradcam,gaussian_blur,2,0.231,0.099,22
24,deletion,gradcam,minimum-intensity,0,0.599,0.155,73
25,deletion,gradcam,minimum-intensity,1,0.205,0.060,21
26,deletion,gradcam,minimum-intensity,2,0.164,0.056,22
27,deletion,gradcam,white-5,0,0.348,0.089,73
28,deletion,gradcam,white-5,1,0.229,0.070,21
29,deletion,gradcam,white-5,2,0.159,0.105,22
30,deletion,hires_cam,attention_mask,0,0.721,0.082,73
31,deletion,hires_cam,attention_mask,1,0.393,0.070,21
32,deletion,hires_cam,attention_mask,2,0.251,0.166,22
33,deletion,hires_cam,black-5,0,0.509,0.137,73
34,deletion,hires_cam,black-5,1,0.212,0.089,21
35,deletion,hires_cam,black-5,2,0.167,0.083,22
36,deletion,hires_cam,gaussian_blur,0,0.660,0.096,73
37,deletion,hires_cam,gaussian_blur,1,0.168,0.049,21
38,deletion,hires_cam,gaussian_blur,2,0.221,0.108,22
39,deletion,hires_cam,minimum-intensity,0,0.741,0.087,73
40,deletion,hires_cam,minimum-intensity,1,0.247,0.101,21
41,deletion,hires_cam,minimum-intensity,2,0.202,0.103,22
42,deletion,hires_cam,white-5,0,0.450,0.136,73
43,deletion,hires_cam,white-5,1,0.361,0.148,21
44,deletion,hires_cam,white-5,2,0.280,0.148,22
45,deletion,last_layer,attention_mask,0,0.658,0.101,73
46,deletion,last_layer,attention_mask,1,0.416,0.104,21
47,deletion,last_layer,attention_mask,2,0.233,0.163,22
48,deletion,last_layer,black-5,0,0.391,0.137,73
49,deletion,last_layer,black-5,1,0.223,0.073,21
50,deletion,last_layer,black-5,2,0.182,0.083,22
51,deletion,last_layer,gaussian_blur,0,0.609,0.136,73
52,deletion,last_layer,gaussian_blur,1,0.187,0.062,21
53,deletion,last_layer,gaussian_blur,2,0.259,0.126,22
54,deletion,last_layer,minimum-intensity,0,0.579,0.118,73
55,deletion,last_layer,minimum-intensity,1,0.280,0.090,21
56,deletion,last_layer,minimum-intensity,2,0.212,0.093,22
57,deletion,last_layer,white-5,0,0.402,0.096,73
58,deletion,last_layer,white-5,1,0.428,0.136,21
59,deletion,last_layer,white-5,2,0.267,0.131,22
60,deletion,slice_weighted_rollout,attention_mask,0,0.563,0.073,73
61,deletion,slice_weighted_rollout,attention_mask,1,0.460,0.075,21
62,deletion,slice_weighted_rollout,attention_mask,2,0.221,0.153,22
63,deletion,slice_weighted_rollout,black-5,0,0.475,0.132,73
64,deletion,slice_weighted_rollout,black-5,1,0.218,0.082,21
65,deletion,slice_weighted_rollout,black-5,2,0.122,0.037,22
66,deletion,slice_weighted_rollout,gaussian_blur,0,0.639,0.150,73
67,deletion,slice_weighted_rollout,gaussian_blur,1,0.200,0.072,21
68,deletion,slice_weighted_rollout,gaussian_blur,2,0.233,0.110,22
69,deletion,slice_weighted_rollout,minimum-intensity,0,0.622,0.105,73
70,deletion,slice_weighted_rollout,minimum-intensity,1,0.278,0.114,21
71,deletion,slice_weighted_rollout,minimum-intensity,2,0.224,0.087,22
72,deletion,slice_weighted_rollout,white-5,0,0.436,0.127,73
73,deletion,slice_weighted_rollout,white-5,1,0.341,0.131,21
74,deletion,slice_weighted_rollout,white-5,2,0.299,0.162,22

## Macro Average

In [13]:
macro_summary = (
    class_summary
    .groupby(["mode", "xai_method", "replacement"])["mean"]
    .mean()
    .reset_index(name="macro_mean_auc")
)

print("=== Macro-average (class-balanced) ===")
macro_summary

=== Macro-average (class-balanced) ===

         mode              xai_method        replacement  macro_mean_auc
0    deletion                grad_sam     attention_mask        0.344667
1    deletion                grad_sam            black-5        0.247667
2    deletion                grad_sam      gaussian_blur        0.355667
3    deletion                grad_sam  minimum-intensity        0.315333
4    deletion                grad_sam            white-5        0.290000
5    deletion                 gradcam     attention_mask        0.348333
6    deletion                 gradcam            black-5        0.267333
7    deletion                 gradcam      gaussian_blur        0.316333
8    deletion                 gradcam  minimum-intensity        0.322667
9    deletion                 gradcam            white-5        0.245333
10   deletion               hires_cam     attention_mask        0.455000
11   deletion               hires_cam            black-5        0.296000
12   deletion               hires_cam      gaussian_blur        0.349667
13   deletion               hires_cam  minimum-intensity        0.396667
14   deletion               hires_cam            white-5        0.363667
15   deletion              last_layer     attention_mask        0.435667
16   deletion              last_layer            black-5        0.265333
17   deletion              last_layer      gaussian_blur        0.351667
18   deletion              last_layer  minimum-intensity        0.357000
19   deletion              last_layer            white-5        0.365667
20   deletion  slice_weighted_rollout     attention_mask        0.414667
21   deletion  slice_weighted_rollout            black-5        0.271667
22   deletion  slice_weighted_rollout      gaussian_blur        0.357333
23   deletion  slice_weighted_rollout  minimum-intensity        0.374667
24   deletion  slice_weighted_rollout            white-5        0.358667
25  insertion                grad_sam     attention_mask        0.736667
26  insertion                grad_sam            black-5        0.540333
27  insertion                grad_sam      gaussian_blur        0.620000
28  insertion                grad_sam  minimum-intensity        0.712000
29  insertion                grad_sam            white-5        0.637333
30  insertion                 gradcam     attention_mask        0.750667
31  insertion                 gradcam            black-5        0.486667
32  insertion                 gradcam      gaussian_blur        0.628667
33  insertion                 gradcam  minimum-intensity        0.750000
34  insertion                 gradcam            white-5        0.704667
35  insertion               hires_cam     attention_mask        0.718667
36  insertion               hires_cam            black-5        0.501667
37  insertion               hires_cam      gaussian_blur        0.611333
38  insertion               hires_cam  minimum-intensity        0.688000
39  insertion               hires_cam            white-5        0.618000
40  insertion              last_layer     attention_mask        0.723667
41  insertion              last_layer            black-5        0.473333
42  insertion              last_layer      gaussian_blur        0.597667
43  insertion              last_layer  minimum-intensity        0.702333
44  insertion              last_layer            white-5        0.604667
45  insertion  slice_weighted_rollout     attention_mask        0.767000
46  insertion  slice_weighted_rollout            black-5        0.609333
47  insertion  slice_weighted_rollout      gaussian_blur        0.636000
48  insertion  slice_weighted_rollout  minimum-intensity        0.734667
49  insertion  slice_weighted_rollout            white-5        0.649333
50   negative                grad_sam     attention_mask        0.736000
51   negative                grad_sam            black-5        0.540667
52   negative                grad_sam      gaussian_blur        0.619667
53   negative                grad_sam  minimum-intensity        0.712000
54   negative                grad_sam            white-5        0.637333
55   negative                 gradcam     attention_mask        0.750667
56   negative                 gradcam            black-5        0.488000
57   negative                 gradcam      gaussian_blur        0.627000
58   negative                 gradcam  minimum-intensity        0.749000
59   negative                 gradcam            white-5        0.702667
60   negative               hires_cam     attention_mask        0.718000
61   negative               hires_cam            black-5        0.502667
62   negative               hires_cam      gaussian_blur        0.610667
63   negative               hires_cam  minimum-intensity        0.688667
64   negative               hires_cam            white-5        0.617667
65   negative              last_layer     attention_mask        0.724333
66   negative              last_layer            black-5        0.474333
67   negative              last_layer      gaussian_blur        0.597667
68   negative              last_layer  minimum-intensity        0.702333
69   negative              last_layer            white-5        0.605000
70   negative  slice_weighted_rollout     attention_mask        0.767333
71   negative  slice_weighted_rollout            black-5        0.609333
72   negative  slice_weighted_rollout      gaussian_blur        0.636333
73   negative  slice_weighted_rollout  minimum-intensity        0.735333
74   negative  slice_weighted_rollout            white-5        0.650000

In [14]:
macro_summary = (
    df_all
    .groupby(["mode", "xai_method", "replacement", "predicted_class"])["auc"]
    .mean()
    .groupby(["mode", "xai_method", "replacement"])
    .agg(macro_mean_auc="mean", macro_std_auc="std", count="count")
    .reset_index()
)
macro_summary["macro_mean_auc"] = macro_summary["macro_mean_auc"].round(3)
macro_summary["macro_std_auc"] = macro_summary["macro_std_auc"].round(3)
print("=== Macro-average (class-balanced) ===")
macro_summary

=== Macro-average (class-balanced) ===

,mode,xai_method,replacement,macro_mean_auc,macro_std_auc,count
0,deletion,grad_sam,attention_mask,0.345,0.194,3
1,deletion,grad_sam,black-5,0.248,0.089,3
2,deletion,grad_sam,gaussian_blur,0.356,0.235,3
3,deletion,grad_sam,minimum-intensity,0.315,0.176,3
4,deletion,grad_sam,white-5,0.290,0.103,3
5,deletion,gradcam,attention_mask,0.348,0.198,3
6,deletion,gradcam,black-5,0.267,0.107,3
7,deletion,gradcam,gaussian_blur,0.316,0.196,3
8,deletion,gradcam,minimum-intensity,0.323,0.240,3
9,deletion,gradcam,white-5,0.245,0.095,3
10,deletion,hires_cam,attention_mask,0.455,0.241,3
11,deletion,hires_cam,black-5,0.296,0.186,3
12,deletion,hires_cam,gaussian_blur,0.350,0.270,3
13,deletion,hires_cam,minimum-intensity,0.397,0.299,3
14,deletion,hires_cam,white-5,0.364,0.085,3
15,deletion,last_layer,attention_mask,0.436,0.213,3
16,deletion,last_layer,black-5,0.266,0.111,3
17,deletion,last_layer,gaussian_blur,0.351,0.226,3
18,deletion,last_layer,minimum-intensity,0.357,0.195,3
19,deletion,last_layer,white-5,0.366,0.086,3
20,deletion,slice_weighted_rollout,attention_mask,0.415,0.175,3
21,deletion,slice_weighted_rollout,black-5,0.272,0.182,3
22,deletion,slice_weighted_rollout,gaussian_blur,0.357,0.245,3
23,deletion,slice_weighted_rollout,minimum-intensity,0.375,0.216,3
24,deletion,slice_weighted_rollout,white-5,0.359,0.070,3
25,insertion,grad_sam,attention_mask,0.737,0.188,3
26,insertion,grad_sam,black-5,0.540,0.172,3
27,insertion,grad_sam,gaussian_blur,0.620,0.155,3
28,insertion,grad_sam,minimum-intensity,0.712,0.108,3
29,insertion,grad_sam,white-5,0.637,0.184,3
30,insertion,gradcam,attention_mask,0.751,0.110,3
31,insertion,gradcam,black-5,0.487,0.081,3
32,insertion,gradcam,gaussian_blur,0.629,0.083,3
33,insertion,gradcam,minimum-intensity,0.750,0.069,3
34,insertion,gradcam,white-5,0.705,0.068,3
35,insertion,hires_cam,attention_mask,0.718,0.173,3
36,insertion,hires_cam,black-5,0.502,0.147,3
37,insertion,hires_cam,gaussian_blur,0.611,0.148,3
38,insertion,hires_cam,minimum-intensity,0.688,0.143,3
39,insertion,hires_cam,white-5,0.618,0.183,3
40,insertion,last_layer,attention_mask,0.724,0.178,3
41,insertion,last_layer,black-5,0.474,0.144,3
42,insertion,last_layer,gaussian_blur,0.598,0.150,3
43,insertion,last_layer,minimum-intensity,0.702,0.137,3
44,insertion,last_layer,white-5,0.605,0.187,3
45,insertion,slice_weighted_rollout,attention_mask,0.767,0.125,3
46,insertion,slice_weighted_rollout,black-5,0.609,0.171,3
47,insertion,slice_weighted_rollout,gaussian_blur,0.636,0.166,3
48,insertion,slice_weighted_rollout,minimum-intensity,0.735,0.093,3
49,insertion,slice_weighted_rollout,white-5,0.650,0.165,3
50,negative,grad_sam,attention_mask,0.736,0.188,3
51,negative,grad_sam,black-5,0.541,0.172,3
52,negative,grad_sam,gaussian_blur,0.620,0.156,3
53,negative,grad_sam,minimum-intensity,0.712,0.108,3
54,negative,grad_sam,white-5,0.637,0.184,3
55,negative,gradcam,attention_mask,0.751,0.112,3
56,negative,gradcam,black-5,0.488,0.080,3
57,negative,gradcam,gaussian_blur,0.627,0.081,3
58,negative,gradcam,minimum-intensity,0.749,0.069,3
59,negative,gradcam,white-5,0.703,0.066,3
60,negative,hires_cam,attention_mask,0.718,0.173,3
61,negative,hires_cam,black-5,0.502,0.146,3
62,negative,hires_cam,gaussian_blur,0.611,0.148,3
63,negative,hires_cam,minimum-intensity,0.689,0.143,3
64,negative,hires_cam,white-5,0.618,0.185,3
65,negative,last_layer,attention_mask,0.724,0.177,3
66,negative,last_layer,black-5,0.474,0.144,3
67,negative,last_layer,gaussian_blur,0.598,0.150,3
68,negative,last_layer,minimum-intensity,0.703,0.136,3
69,negative,last_layer,white-5,0.605,0.187,3
70,negative,slice_weighted_rollout,attention_mask,0.767,0.124,3
71,negative,slice_weighted_rollout,black-5,0.609,0.172,3
72,negative,slice_weighted_rollout,gaussian_blur,0.636,0.167,3
73,negative,slice_weighted_rollout,minimum-intensity,0.735,0.094,3
74,negative,slice_weighted_rollout,white-5,0.650,0.165,3

## Combine Micro and Macro average

In [15]:
replacement_order = [
    "black-5",
    "minimum-intensity",
    "white-5",
    "gaussian_blur",
    "attention_mask"
]

In [16]:
combined_summary = (
    micro_summary
    .rename(columns={"mean": "micro_mean_auc", "std": "micro_std_auc"})
    .merge(macro_summary, on=["mode", "xai_method", "replacement"])
)

print("=== Combined Summary ===")
combined_summary

=== Combined Summary ===

,mode,xai_method,replacement,micro_mean_auc,micro_std_auc,count_x,macro_mean_auc,macro_std_auc,count_y
0,deletion,grad_sam,attention_mask,0.419,0.178,116,0.345,0.194,3
1,deletion,grad_sam,black-5,0.293,0.133,116,0.248,0.089,3
2,deletion,grad_sam,gaussian_blur,0.473,0.238,116,0.356,0.235,3
3,deletion,grad_sam,minimum-intensity,0.406,0.181,116,0.315,0.176,3
4,deletion,grad_sam,white-5,0.314,0.114,116,0.290,0.103,3
5,deletion,gradcam,attention_mask,0.426,0.196,116,0.348,0.198,3
6,deletion,gradcam,black-5,0.315,0.148,116,0.267,0.107,3
7,deletion,gradcam,gaussian_blur,0.416,0.197,116,0.316,0.196,3
8,deletion,gradcam,minimum-intensity,0.445,0.239,116,0.323,0.240,3
9,deletion,gradcam,white-5,0.290,0.118,116,0.245,0.095,3
10,deletion,hires_cam,attention_mask,0.572,0.223,116,0.455,0.241,3
11,deletion,hires_cam,black-5,0.390,0.197,116,0.296,0.186,3
12,deletion,hires_cam,gaussian_blur,0.488,0.244,116,0.350,0.270,3
13,deletion,hires_cam,minimum-intensity,0.549,0.267,116,0.397,0.299,3
14,deletion,hires_cam,white-5,0.402,0.155,116,0.364,0.085,3
15,deletion,last_layer,attention_mask,0.533,0.207,116,0.436,0.213,3
16,deletion,last_layer,black-5,0.321,0.150,116,0.266,0.111,3
17,deletion,last_layer,gaussian_blur,0.466,0.225,116,0.351,0.226,3
18,deletion,last_layer,minimum-intensity,0.455,0.196,116,0.357,0.195,3
19,deletion,last_layer,white-5,0.381,0.124,116,0.366,0.086,3
20,deletion,slice_weighted_rollout,attention_mask,0.480,0.161,116,0.415,0.175,3
21,deletion,slice_weighted_rollout,black-5,0.361,0.188,116,0.272,0.182,3
22,deletion,slice_weighted_rollout,gaussian_blur,0.482,0.243,116,0.357,0.245,3
23,deletion,slice_weighted_rollout,minimum-intensity,0.484,0.208,116,0.375,0.216,3
24,deletion,slice_weighted_rollout,white-5,0.393,0.146,116,0.359,0.070,3
25,insertion,grad_sam,attention_mask,0.789,0.155,116,0.737,0.188,3
26,insertion,grad_sam,black-5,0.564,0.184,116,0.540,0.172,3
27,insertion,grad_sam,gaussian_blur,0.584,0.170,116,0.620,0.155,3
28,insertion,grad_sam,minimum-intensity,0.757,0.143,116,0.712,0.108,3
29,insertion,grad_sam,white-5,0.564,0.204,116,0.637,0.184,3
30,insertion,gradcam,attention_mask,0.795,0.111,116,0.751,0.110,3
31,insertion,gradcam,black-5,0.528,0.143,116,0.487,0.081,3
32,insertion,gradcam,gaussian_blur,0.644,0.117,116,0.629,0.083,3
33,insertion,gradcam,minimum-intensity,0.785,0.103,116,0.750,0.069,3
34,insertion,gradcam,white-5,0.672,0.130,116,0.705,0.068,3
35,insertion,hires_cam,attention_mask,0.764,0.147,116,0.718,0.173,3
36,insertion,hires_cam,black-5,0.501,0.170,116,0.502,0.147,3
37,insertion,hires_cam,gaussian_blur,0.618,0.149,116,0.611,0.148,3
38,insertion,hires_cam,minimum-intensity,0.747,0.170,116,0.688,0.143,3
39,insertion,hires_cam,white-5,0.550,0.206,116,0.618,0.183,3
40,insertion,last_layer,attention_mask,0.762,0.155,116,0.724,0.178,3
41,insertion,last_layer,black-5,0.517,0.179,116,0.474,0.144,3
42,insertion,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
43,insertion,last_layer,minimum-intensity,0.753,0.152,116,0.702,0.137,3
44,insertion,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
45,insertion,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.125,3
46,insertion,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.171,3
47,insertion,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.166,3
48,insertion,slice_weighted_rollout,minimum-intensity,0.760,0.138,116,0.735,0.093,3
49,insertion,slice_weighted_rollout,white-5,0.580,0.184,116,0.650,0.165,3
50,negative,grad_sam,attention_mask,0.788,0.156,116,0.736,0.188,3
51,negative,grad_sam,black-5,0.564,0.184,116,0.541,0.172,3
52,negative,grad_sam,gaussian_blur,0.584,0.169,116,0.620,0.156,3
53,negative,grad_sam,minimum-intensity,0.757,0.143,116,0.712,0.108,3
54,negative,grad_sam,white-5,0.565,0.204,116,0.637,0.184,3
55,negative,gradcam,attention_mask,0.795,0.110,116,0.751,0.112,3
56,negative,gradcam,black-5,0.529,0.139,116,0.488,0.080,3
57,negative,gradcam,gaussian_blur,0.643,0.117,116,0.627,0.081,3
58,negative,gradcam,minimum-intensity,0.784,0.103,116,0.749,0.069,3
59,negative,gradcam,white-5,0.671,0.133,116,0.703,0.066,3
60,negative,hires_cam,attention_mask,0.763,0.148,116,0.718,0.173,3
61,negative,hires_cam,black-5,0.500,0.169,116,0.502,0.146,3
62,negative,hires_cam,gaussian_blur,0.616,0.150,116,0.611,0.148,3
63,negative,hires_cam,minimum-intensity,0.748,0.171,116,0.689,0.143,3
64,negative,hires_cam,white-5,0.547,0.207,116,0.618,0.185,3
65,negative,last_layer,attention_mask,0.762,0.155,116,0.724,0.177,3
66,negative,last_layer,black-5,0.517,0.180,116,0.474,0.144,3
67,negative,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
68,negative,last_layer,minimum-intensity,0.754,0.151,116,0.703,0.136,3
69,negative,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
70,negative,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.124,3
71,negative,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.172,3
72,negative,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.167,3
73,negative,slice_weighted_rollout,minimum-intensity,0.761,0.137,116,0.735,0.094,3
74,negative,slice_weighted_rollout,white-5,0.581,0.184,116,0.650,0.165,3

In [17]:
combined_summary["replacement"] = pd.Categorical(
    combined_summary["replacement"],
    categories=replacement_order,
    ordered=True
)

In [18]:
combined_summary = combined_summary.sort_values(
    by=["mode", "xai_method", "replacement"]
).reset_index(drop=True)

In [19]:
combined_summary

,mode,xai_method,replacement,micro_mean_auc,micro_std_auc,count_x,macro_mean_auc,macro_std_auc,count_y
0,deletion,grad_sam,black-5,0.293,0.133,116,0.248,0.089,3
1,deletion,grad_sam,minimum-intensity,0.406,0.181,116,0.315,0.176,3
2,deletion,grad_sam,white-5,0.314,0.114,116,0.290,0.103,3
3,deletion,grad_sam,gaussian_blur,0.473,0.238,116,0.356,0.235,3
4,deletion,grad_sam,attention_mask,0.419,0.178,116,0.345,0.194,3
5,deletion,gradcam,black-5,0.315,0.148,116,0.267,0.107,3
6,deletion,gradcam,minimum-intensity,0.445,0.239,116,0.323,0.240,3
7,deletion,gradcam,white-5,0.290,0.118,116,0.245,0.095,3
8,deletion,gradcam,gaussian_blur,0.416,0.197,116,0.316,0.196,3
9,deletion,gradcam,attention_mask,0.426,0.196,116,0.348,0.198,3
10,deletion,hires_cam,black-5,0.390,0.197,116,0.296,0.186,3
11,deletion,hires_cam,minimum-intensity,0.549,0.267,116,0.397,0.299,3
12,deletion,hires_cam,white-5,0.402,0.155,116,0.364,0.085,3
13,deletion,hires_cam,gaussian_blur,0.488,0.244,116,0.350,0.270,3
14,deletion,hires_cam,attention_mask,0.572,0.223,116,0.455,0.241,3
15,deletion,last_layer,black-5,0.321,0.150,116,0.266,0.111,3
16,deletion,last_layer,minimum-intensity,0.455,0.196,116,0.357,0.195,3
17,deletion,last_layer,white-5,0.381,0.124,116,0.366,0.086,3
18,deletion,last_layer,gaussian_blur,0.466,0.225,116,0.351,0.226,3
19,deletion,last_layer,attention_mask,0.533,0.207,116,0.436,0.213,3
20,deletion,slice_weighted_rollout,black-5,0.361,0.188,116,0.272,0.182,3
21,deletion,slice_weighted_rollout,minimum-intensity,0.484,0.208,116,0.375,0.216,3
22,deletion,slice_weighted_rollout,white-5,0.393,0.146,116,0.359,0.070,3
23,deletion,slice_weighted_rollout,gaussian_blur,0.482,0.243,116,0.357,0.245,3
24,deletion,slice_weighted_rollout,attention_mask,0.480,0.161,116,0.415,0.175,3
25,insertion,grad_sam,black-5,0.564,0.184,116,0.540,0.172,3
26,insertion,grad_sam,minimum-intensity,0.757,0.143,116,0.712,0.108,3
27,insertion,grad_sam,white-5,0.564,0.204,116,0.637,0.184,3
28,insertion,grad_sam,gaussian_blur,0.584,0.170,116,0.620,0.155,3
29,insertion,grad_sam,attention_mask,0.789,0.155,116,0.737,0.188,3
30,insertion,gradcam,black-5,0.528,0.143,116,0.487,0.081,3
31,insertion,gradcam,minimum-intensity,0.785,0.103,116,0.750,0.069,3
32,insertion,gradcam,white-5,0.672,0.130,116,0.705,0.068,3
33,insertion,gradcam,gaussian_blur,0.644,0.117,116,0.629,0.083,3
34,insertion,gradcam,attention_mask,0.795,0.111,116,0.751,0.110,3
35,insertion,hires_cam,black-5,0.501,0.170,116,0.502,0.147,3
36,insertion,hires_cam,minimum-intensity,0.747,0.170,116,0.688,0.143,3
37,insertion,hires_cam,white-5,0.550,0.206,116,0.618,0.183,3
38,insertion,hires_cam,gaussian_blur,0.618,0.149,116,0.611,0.148,3
39,insertion,hires_cam,attention_mask,0.764,0.147,116,0.718,0.173,3
40,insertion,last_layer,black-5,0.517,0.179,116,0.474,0.144,3
41,insertion,last_layer,minimum-intensity,0.753,0.152,116,0.702,0.137,3
42,insertion,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
43,insertion,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
44,insertion,last_layer,attention_mask,0.762,0.155,116,0.724,0.178,3
45,insertion,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.171,3
46,insertion,slice_weighted_rollout,minimum-intensity,0.760,0.138,116,0.735,0.093,3
47,insertion,slice_weighted_rollout,white-5,0.580,0.184,116,0.650,0.165,3
48,insertion,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.166,3
49,insertion,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.125,3
50,negative,grad_sam,black-5,0.564,0.184,116,0.541,0.172,3
51,negative,grad_sam,minimum-intensity,0.757,0.143,116,0.712,0.108,3
52,negative,grad_sam,white-5,0.565,0.204,116,0.637,0.184,3
53,negative,grad_sam,gaussian_blur,0.584,0.169,116,0.620,0.156,3
54,negative,grad_sam,attention_mask,0.788,0.156,116,0.736,0.188,3
55,negative,gradcam,black-5,0.529,0.139,116,0.488,0.080,3
56,negative,gradcam,minimum-intensity,0.784,0.103,116,0.749,0.069,3
57,negative,gradcam,white-5,0.671,0.133,116,0.703,0.066,3
58,negative,gradcam,gaussian_blur,0.643,0.117,116,0.627,0.081,3
59,negative,gradcam,attention_mask,0.795,0.110,116,0.751,0.112,3
60,negative,hires_cam,black-5,0.500,0.169,116,0.502,0.146,3
61,negative,hires_cam,minimum-intensity,0.748,0.171,116,0.689,0.143,3
62,negative,hires_cam,white-5,0.547,0.207,116,0.618,0.185,3
63,negative,hires_cam,gaussian_blur,0.616,0.150,116,0.611,0.148,3
64,negative,hires_cam,attention_mask,0.763,0.148,116,0.718,0.173,3
65,negative,last_layer,black-5,0.517,0.180,116,0.474,0.144,3
66,negative,last_layer,minimum-intensity,0.754,0.151,116,0.703,0.136,3
67,negative,last_layer,white-5,0.530,0.202,116,0.605,0.187,3
68,negative,last_layer,gaussian_blur,0.569,0.164,116,0.598,0.150,3
69,negative,last_layer,attention_mask,0.762,0.155,116,0.724,0.177,3
70,negative,slice_weighted_rollout,black-5,0.584,0.150,116,0.609,0.172,3
71,negative,slice_weighted_rollout,minimum-intensity,0.761,0.137,116,0.735,0.094,3
72,negative,slice_weighted_rollout,white-5,0.581,0.184,116,0.650,0.165,3
73,negative,slice_weighted_rollout,gaussian_blur,0.585,0.188,116,0.636,0.167,3
74,negative,slice_weighted_rollout,attention_mask,0.793,0.129,116,0.767,0.124,3

## Method Comparison

In [20]:
method_summary = (
    df_all.groupby(["mode", "xai_method"])["auc"]
    .agg(["mean", "std"])
    .reset_index()
)

print("=== Method comparison ===")
method_summary

=== Method comparison ===

         mode              xai_method      mean       std
0    deletion                grad_sam  0.380976  0.186351
1    deletion                 gradcam  0.378708  0.194210
2    deletion               hires_cam  0.480312  0.232148
3    deletion              last_layer  0.431473  0.197616
4    deletion  slice_weighted_rollout  0.440078  0.198635
5   insertion                grad_sam  0.651726  0.198937
6   insertion                 gradcam  0.684960  0.156245
7   insertion               hires_cam  0.635888  0.198971
8   insertion              last_layer  0.626326  0.202442
9   insertion  slice_weighted_rollout  0.660452  0.185519
10   negative                grad_sam  0.651663  0.198795
11   negative                 gradcam  0.684435  0.155632
12   negative               hires_cam  0.635051  0.199687
13   negative              last_layer  0.626569  0.202453
14   negative  slice_weighted_rollout  0.660632  0.185369

## Strategy Comparison

In [21]:
strategy_summary = (
    df_all.groupby(["mode", "replacement"])["auc"]
    .agg(["mean", "std"])
    .reset_index()
)

print("=== Strategy comparison ===")
strategy_summary

=== Strategy comparison ===

         mode        replacement      mean       std
0    deletion     attention_mask  0.486166  0.202385
1    deletion            black-5  0.336209  0.168016
2    deletion      gaussian_blur  0.465210  0.230823
3    deletion  minimum-intensity  0.467846  0.224819
4    deletion            white-5  0.356116  0.139277
5   insertion     attention_mask  0.780533  0.140770
6   insertion            black-5  0.538934  0.168306
7   insertion      gaussian_blur  0.600190  0.161008
8   insertion  minimum-intensity  0.760448  0.143105
9   insertion            white-5  0.579247  0.193351
10   negative     attention_mask  0.780362  0.140760
11   negative            black-5  0.538954  0.167600
12   negative      gaussian_blur  0.599649  0.160844
13   negative  minimum-intensity  0.760647  0.142954
14   negative            white-5  0.578739  0.193820

## Best Method

In [22]:
# For deletion → lower is better
best_deletion = micro_summary[micro_summary["mode"] == "deletion"].sort_values("mean")

# For insertion → higher is better
best_insertion = micro_summary[micro_summary["mode"] == "insertion"].sort_values("mean", ascending=False)

print("=== Best (Deletion) ===")
print(best_deletion.head())

print("\n=== Best (Insertion) ===")
print(best_insertion.head())

=== Best (Deletion) ===
        mode  xai_method replacement   mean    std  count
9   deletion     gradcam     white-5  0.290  0.118    116
1   deletion    grad_sam     black-5  0.293  0.133    116
4   deletion    grad_sam     white-5  0.314  0.114    116
6   deletion     gradcam     black-5  0.315  0.148    116
16  deletion  last_layer     black-5  0.321  0.150    116

=== Best (Insertion) ===
         mode              xai_method        replacement   mean    std  count
30  insertion                 gradcam     attention_mask  0.795  0.111    116
45  insertion  slice_weighted_rollout     attention_mask  0.793  0.129    116
25  insertion                grad_sam     attention_mask  0.789  0.155    116
33  insertion                 gradcam  minimum-intensity  0.785  0.103    116
35  insertion               hires_cam     attention_mask  0.764  0.147    116

## Save Everythings

In [23]:
micro_summary.to_csv("micro_summary.csv", index=False)
class_summary.to_csv("class_summary.csv", index=False)
macro_summary.to_csv("macro_summary.csv", index=False)
method_summary.to_csv("method_summary.csv", index=False)
strategy_summary.to_csv("strategy_summary.csv", index=False)

print("All results saved")

All results saved

# Calculate curve again without Normalized Confidence

In [24]:
evaluation_methods = {
    "deletion": "Deletion",
    "insertion": "Insertion",
    "negative": "Negative Perturbation",
}

replacement_strategies = {
    "black-5": "Black masking", 
    "minimum-intensity": "Minimum intensity",
    "white-5": "White masking", 
    "gaussian_blur": "Gaussian Blur",
    "attention_mask" : "Attention Mask",  
}

xai_methods = {
    "gradcam": "Grad-CAM",
    "last_layer": "Last-layer attention", 
    "slice_weighted_rollout": "Attention rollout" 
}

colors = {
    "gradcam": "#1f77b4",              # blue
    "last_layer": "#ff7f0e",           # orange
    "slice_weighted_rollout": "#2ca02c"  # green
}

In [25]:
import numpy as np
from pathlib import Path
base_path = Path("/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results")
test_data = np.load("/home/jovyan/work/MST/results/DINOv3ViTB/evaluation_results/deletion/deletion_curves/gradcam/attention_mask/02F4A1FB_left_curve_attention_mask.npy", allow_pickle=True).item()
test_data.keys()

dict_keys(['percentages', 'raw_logits', 'confidences', 'normalized_confidences', 'predicted_class', 'predicted_confidences', 'predicted_normalized_confidences', 'auc', 'replacement'])